CustomerWebsite:
  CustomerApiUrl:
    settings-key: CustomerApiUrl
  PartnerApiUrl:
    settings-key: PartnerApiUrl
  AndroidLink:
    settings-key: CustomerWebsite-AndroidLink
  IosLink:
    settings-key: CustomerWebsite-IosLink
