apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-website
    environment: Development
  name: customer-website
  namespace: frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: customer-website
  sessionAffinity: None
  type: ClusterIP
